FROM php:7.4-fpm-alpine
MAINTAINER Tino Naumann <mail@ti-no.de>

RUN apk add --update-cache tzdata shadow  \
  && usermod -u 1000 www-data             \
  && groupmod -g 1000 www-data

RUN apk add --update-cache libzip-dev libpng-dev  \
  && docker-php-ext-install mysqli                \
  && docker-php-ext-install pdo_mysql             \
  && docker-php-ext-install gd                    \
  && docker-php-ext-install zip                   \
  && rm -rf /var/cache/apk/*
COPY rootfs /
RUN mv /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
  && rm /usr/local/etc/php/php.ini-development

RUN mkdir -p /var/www/html/public/ /var/www/logs/php/ /var/www/configs/php/ /var/www/bin/                 \
  && chown www-data:www-data /var/www/html/public/ /var/www/logs/php/ /var/www/configs/php/ /var/www/bin/
USER www-data:www-data
RUN mkdir -p /var/www/bin/.composer                                                                                                       \
  && curl -sS https://getcomposer.org/installer | php -- --install-dir=/var/www/bin --filename=composer                                   \
  && /var/www/bin/composer create-project processwire/processwire public -d /var/www/html/                                                \
  && curl -sSL https://www.adminer.org/latest-mysql.php -o /var/www/html/public/db.php                                                    \
  && curl -sSL https://raw.githubusercontent.com/vrana/adminer/master/designs/pepa-linha/adminer.css -o /var/www/html/public/adminer.css

ENV PATH /var/www/bin:$PATH
VOLUME ["/var/www"]
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["php-fpm"]